global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: traefik
    static_configs:
      - targets:
          - traefik:8080

  - job_name: rabbitmq
    static_configs:
      - targets:
          - rabbitmq:15692

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets:
        - minio:9000

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
